"""add_is_archived_to_conversations

Revision ID: 32043dd26a2b
Revises: defb1012e682
Create Date: 2026-08-31 23:12:36.723763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32043dd26a2b'
down_revision: Union[str, Sequence[str], None] = 'defb1012e682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('conversations', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_archived')
    # ### end Alembic commands ###
